  
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone-project
  region: us-east-1

managedNodeGroups:
  - name: nodegroup
    instanceType: t2.micro
    minSize: 2
    maxSize: 2
    desiredCapacity: 1
    availabilityZones: ["us-east-1a", "us-east-1b"]
    volumeSize: 20
    ssh:
      publicKeyName: udacity
